name: list-repo

on:
  push:
    branches:
      - main

jobs:
  list-repo-files:
    name: count lines of codes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Directory
        run: |
          find . -type f

      - name: Install pygount
        run: |
          python -m pip install pygount

      - name: Count Lines of Code
        run: |
          pygount --format=table .

